spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:employee
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  application:
    name: employee-app
server:
  port:  ${EMPLOYEE-APP:8080}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka
management:
  endpoints:
    web:
      exposure:
        include: "*"

  info:
    env:
      enabled: true